apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-mysql
spec:
  selector:
    matchLabels:
      app: payment-mysql
  template:
    metadata:
      labels:
        app: payment-mysql
    spec:
      containers:
        - name: payment-mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: paymentdb
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: payment-mysql
spec:
  selector:
    app: payment-mysql
  ports:
    - port: 3306
      targetPort: 3306
